name: Test in docker

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/ci.yml' # monitor the main workflow script.
      - 'run_pross_parallel.sh'
      - 'scripts/*'
      - 'utils/*'

    branches:
        - main

env: 
  conda_env: PROSS

jobs:
  DevTests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        python-version: 
          # - "3.9"
          # - "3.10"
          - "3.11"

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

  

    container: 
      image: rosettacommons/rosetta:latest


    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Conda on ${{ matrix.os }}
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: false
            activate-environment: ${{ env.conda_env }}
            auto-activate-base: false
            python-version: ${{ matrix.python-version }}
      
      - name: Setup PyRosetta on ${{ matrix.os }} - py${{ matrix.python-version }}
        run: |
          conda info
          conda list
          which python
          which python3

      - name: Setup test environment
        run: |
          python -V; bash tests/scripts/setup_for_ci.sh
    
      - name: Run testcase - monomer
        run: |
            bash tests/scripts/run_3afp_hf3_A.sh
          